"""Core schemas and taxonomy. Depends on nothing else inside RedSI."""

from redsi.core.models import (
    Assessment,
    CaseRecord,
    Document,
    EvaluationResult,
    EvaluatorSpec,
    Finding,
    FindingStatus,
    Hypothesis,
    Message,
    Origin,
    Relation,
    Reproducibility,
    RootCause,
    TargetInput,
    TargetOutput,
    TestCase,
    ToolCall,
    ToolSpec,
    Usage,
    Verdict,
)
from redsi.core.severity import Severity, SeverityPolicy, SeverityRule
from redsi.core.taxonomy import Category, categories, get_category, register_category

__all__ = [
    "Assessment",
    "CaseRecord",
    "Category",
    "Document",
    "EvaluationResult",
    "EvaluatorSpec",
    "Finding",
    "FindingStatus",
    "Hypothesis",
    "Message",
    "Origin",
    "Relation",
    "Reproducibility",
    "RootCause",
    "Severity",
    "SeverityPolicy",
    "SeverityRule",
    "TargetInput",
    "TargetOutput",
    "TestCase",
    "ToolCall",
    "ToolSpec",
    "Usage",
    "Verdict",
    "categories",
    "get_category",
    "register_category",
]
